export const APPEND_DIGIT = 'APPEND_DIGIT';
export const APPEND_OPERATOR = 'APPEND_OPERATOR';
export const CHOP_EXPRESSION = 'CHOP_EXPRESSION';
export const EVAL_EXPRESSION = 'EVAL_EXPRESSION';
export const SET_EXPRESSION = 'SET_EXPRESSION';
